### PR TITLE
Fixed tense & split list to make a killed idiom

### PR DESCRIPTION
**Pull request by Dgilliams**

### CODE REVIEW

**Comment by codyogden** [comment]
I'd rather stick with only having the idioms on pending deaths. Since those idioms update every time the state is changed, the user input response performance takes a hit when there are that many of them.

**Comment by Dgilliams** [comment]
Didn't realize that. I definitely agree for the sake of performance. Also, I thought about it and having all the dead ones say "killed" is better for branding. Even better for branding would be if they all said "Killed by Google..."

Want me to put them all back to the pending death idiom and change it to "Killed by Google"?

**Comment by codyogden** [comment]
I think the original "Killed" for dead products is fine. Obituaries generally avoid mentioning a victim's killer's name in the eulogy.  😆

So, keep the new grammatically appropriate idioms, and revert to the original sentence structure. Then it should be good to merge!

**Comment by Dgilliams** [comment]
Lol makes sense. I'll make those changes.

**Pull request closed without merging**
