### PR TITLE
Add G Suite legacy free edition

### PR DESCRIPTION
**Pull request by TyBrown**
Hey Cody!

Long time follower... saw this sad news today. :( 

I wasn't quite sure whether to use 2022-05-01, or 2022-07-01 for the `closeDate`, since both dates are referenced in the linked article from Google. I went with the May date for now... happy to change it to July if you think that's more appropriate.

Cheers,
Ty

### CODE REVIEW

**Comment by codyogden** [comment]
Let's link to a the 9to5Google article (or other news article) as the source. I don't like linking to Google's Support docs because they 404 those docs very quickly after the dates listed.

https://9to5google.com/2022/01/19/g-suite-legacy-free-edition/

**Comment by TyBrown** [comment]
Are you okay if I add a commit (or separate PR) to add that guidance to the README?

**Comment by codyogden** [comment]
@TyBrown Sure. Go ahead and add that to the README. You can do it in this PR. Cheers. 😁

**Comment by TyBrown** [comment]
All done... Cheers mate! :) Thanks for the opportunity to contribute.

**Pull request merged**
