### PR TITLE
package updates and TypeScript progress

### PR DESCRIPTION
**Pull request by jrr**
- A bunch of minor package updates
- Move a few `.atom.js` files to TypeScript
- Add a TypeScript compilation step to CI

### CODE REVIEW

**Comment by jrr** [comment]
Whoops, the deploy preview looks broken.

**Comment by jrr** [comment]
@codyogden this PR fixes the build! Can you take a look?

**Comment by jrr** [comment]
Rebased.

**Comment by jrr** [comment]
@codyogden updated packages again and the build's green. Can you take a look? I'd like to follow this with more TypeScript, but am hesitant to diverge further from `master` until this is in.

**Comment by codyogden** [comment]
I’ll have some time this weekend to take a look. :)

**Comment by jrr** [comment]
Rebased and green again.

**Comment by codyogden** [comment]
I converted Killed by Google to Next in #818. I'm closing this PR since we're going to use a framework going forward.

**Pull request closed without merging**
