### PR TITLE
Add YouTube VR (SteamVR)

### PR DESCRIPTION
**Pull request by burritosoftware**
Google quietly killed YouTube VR for SteamVR on December 10th, 2020. While there is no news source I could find on this date, this date was logged by 3rd party Steam trackers like SteamDB.

https://steamdb.info/app/755770/history/

### CODE REVIEW

**Comment by burritosoftware** [comment]
The deploy preview shows 23 days instead of SteamDB's reported 22, so I'm not sure if the date I calculated was put in properly.

**Comment by codyogden** [comment]
So this is an app for Windows? Did they just delete the app because they're pushing Chrome?

**Comment by burritosoftware** [comment]
> So this is an app for Windows? Did they just delete the app because they're pushing Chrome?

Yes, this is an app for Windows. I haven't heard of any Chrome/YouTube VR for web that works with SteamVR headsets as of now.
They deleted the app because it was apparently super buggy and horribly done or something. Looking it up on Steam Community shows a lot of frustration (and the reviews were apparently bad)

**Comment by burritosoftware** [comment]
I should clarify that I mentioned SteamVR specifically as YouTube VR is still maintained on the Quest.

**Pull request merged**
