### PR TITLE
Pixel Slate ain’t dead!

### PR DESCRIPTION
**Pull request by kayvonkamyar**
It’s still in google store!

### CODE REVIEW

**Comment by Espin0606** [comment]
ehh, this doesnt exactly mean that its still alive. Maybe its being sold, but not being supported or updated

**Comment by louistsaitszho** [comment]
It is still being updated and supported, it's just that Google will NOT make another tablet. So the Slate itself is not dead. 

That does raise a question: should normal produce EOL be included in this list?

**Comment by codyogden** [comment]
I'll approve this. We can add it when they stop selling it.

**Comment by upintheairsheep** [comment]
Aged like milk. Dead.

**Pull request merged**
