### PR TITLE
Adding Nexus Player

### PR DESCRIPTION
**Pull request by luckymurari**
Nexus player was a digital media player discontinued with no updates

### CODE REVIEW

**Comment by luckymurari** [comment]
I am unsure why the Travis CI build failed. @codyogden Any ideas or can this be just merged?

**Comment by codyogden** [comment]
@luckymurari I restarted the build. No worries.

**Comment by codyogden** [comment]
Thank you!! 💯 🙌 🥇

**Comment by luckymurari** [comment]
Awesome.

**Pull request merged**
