### PR TITLE
Google specialized search

### PR DESCRIPTION
**Pull request by mskadu**
As requested in issue #608

### CODE REVIEW

**Comment by mskadu** [comment]
Hi @codyogden - is there anything blocking this item from being merged? Anything requiring a fix from me?

**Comment by mskadu** [comment]
Hi @codyogden - any blockers in merging this one pls?

**Comment by codyogden** [comment]
Hello, please review the description guidelines in README.md.

**Comment by mskadu** [comment]
Done. Pls have a look and see if it reads better.

**Comment by mskadu** [comment]
Hi again. Have you had a chance to review this?

**Comment by mskadu** [comment]
Hey @codyogden. Have you had a chance to review these changes yet?

**Pull request merged**
